# -*- coding: utf-8 -*-
"""
Created on Sun Feb 22 16:05:03 2026
Revised on Sun Oct 04 13:02:40 2026

@author: Junxuan Ma
"""

#Segment neuronal pixels that have their corresponding calcium signals.
"""
Generate dataframe informing pixel location and which neuron this pixel belong to.
    In this dataframe, each row represent a pixel.
Later this dataframe will be also used to store 
    immunofluorescent information, and
    calcium imaging quantification.
The pixels will be in the same order comparing dataframe with np.array, 
    which make the link between these 2 types of data.


    Raw calcium imaging data as 2D np.ndarray:

        Shape of (time, pixels).
                    axis 1 →  (pixels)
                    ┌──────┬──────┬──────┬──────┐
         axis 0     │ 0,0  │ 0,1  │ 0,2  │ 0,3  │
         ↓ (time)   ├──────┼──────┼──────┼──────┤
                    │ 1,0  │ 1,1  │ 1,2  │ 1,3  │
                    ├──────┼──────┼──────┼──────┤
                    │ 2,0  │ 2,1  │ 2,2  │ 2,3  │
                    └──────┴──────┴──────┴──────┘
    The dataframe output data (pixels, measured features) is in a long format:

                            measured features (columns) →
                ┌──────┬──────┬────────┬─────────┬──────────┬─────────┬──────────┐
                │  Y   │  X   │Cluster │  Ca_PH  │  Ca_freq │ IF_NF   │ IF_CGRP  │
                ├──────┼──────┼────────┼─────────┼──────────┼─────────┼──────────┤
         pixel0 │  10  │  22  │   1    │  0.85   │   4.2    │  120.3  │  88.1    │
         pixel1 │  10  │  23  │   1    │  0.81   │   3.9    │  118.7  │  90.4    │
         pixel2 │  11  │  22  │   1    │  0.79   │   4.1    │  121.0  │  89.2    │
         pixel3 │  45  │  67  │   2    │  1.02   │   5.6    │   95.4  │ 130.8    │
         pixel4 │  45  │  68  │   2    │ _0.98   │   5.2    │  _94.1  │ _128.9   │
          ...   │ ...  │ ...  │...     │   ...   │   ...    │   ...   │ ...      │
         pixelM │ 201  │ 350  │  37    │  0.64   │   3.1    │  105.2  │  77.5    │
                └──────┴──────┴────────┴─────────┴──────────┴─────────┴──────────┘




Sturcuture of the imgseg.py:
    BG_define (Defining background)
        ├── __init__
        ├── _apply_method
        ├── _compute_thre_mask

        ├── Single_curve_plot
        ├── Thre_plot
        ├── Thre_multi_plot
        └── Cut_background (Port to connect other analysis, e.g., ICA)

    PC_PROJ (Principle component analysis)
        ├── __init__
        ├── _get_full_spatial_component

        ├── Get_PCs
        ├── PCA_plot
        ├── PCA_multi_plot
        └── Dimension_reduction (Port to connect other analysis, e.g., ICA)

    Neuron_Cluster (DBSCAN clustering of pixels in spatial principle components)
        ├── __init__
        ├── _mask_matrix_to_df
        ├── _dbscan
        ├── _clusterwise_process
        ├── _pix_size_filter
        ├── _roundness  (static)
        ├── _roundness_filter

        ├── PC_DBSCAN
        ├── PC_DBSCAN_plot
        ├── PC_index_plot

        ├── __define_parameters__
        ├── _subtract_df1_from_df2
        ├── _z_project

        ├── Z_Project
        └── Z_Project_plot

    Neuron_Seg
        ├── __init__
        ├── _output_all_Cal
        ├── _get_border
        ├── _clusterwise_sub_devide

        ├── Output_core_border
        ├── Output_all_Cal
        └── Output_background

        
The NeuronSeg algorithm contains the following steps:
    1. BG_define: defining background pixels based on threshold defined from the function of 
       Visual_functions.Check_all_threshold.
       
       Inputs (parameters): 
           Calcium_imaging : NDArray[np.float32] or NDArray[np.float64]
               2D array of shape (time, pixels). Can be either ΔF/F₀ or raw fluorescence.

           time_slice_thre1: time window used to threshold based on brightness.
               The time frames within this time window will be
               maximized/meaned/minimized and thresholded to generate mask

           time_slice_thre2_base and time_slice_thre2_peak: used to threshold based on response
               Time windows to define baseline and peak time series
               These two windows of time series will be maximized/meaned/minimized
                   over time to generate single base image and peak image, respectively.
               The mask is generated by thresholding the contrast of peak image - base image
               
           method_1: decide maximized/meaned/minimized of time window defined by time_slice_thre1
           method_2_base and method_2_peak: decide maximized/meaned/minimized of time windows
               defined by time_slice_thre2_base and time_slice_thre2_peak, respectively.

           dim_h and dim_w are the pixel size of calcium imaging.
                It is output of ImportCZI().read_Cal()
           
       Outputs (attributes): 
           Thre_plot() plot the binary mask after thresholding
           Thre_multi_plot() multi-panel plots trying combinations of thresholds
           Cut_background(self,dim_h,dim_w) output:
                A reduced calcium imaging np.array containing only pixels 
                    that are not regarded as background.             
                And a dataframe informing the X and Y position of all selected pixels
                    (pixels that are not regarded as background)
                    corresponding to the reduced calcium imaging data.
               
                 
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from typing import Optional, Sequence
from matplotlib.ticker import MultipleLocator

class BG_define:
    def __init__(
        self,
        Calcium_imaging: np.ndarray,
        dim_h: int,
        dim_w: int,
        time_slice_thre1: Optional[slice] = None,
        time_slice_thre2_base: Optional[slice] = None,
        time_slice_thre2_peak: Optional[slice] = None,
        method_1: str = 'maximum',
        method_2_base: str = 'mean',
        method_2_peak: str = 'mean' 
    ):
        self.cal = np.asarray(Calcium_imaging)
        if self.cal.ndim != 2:
            raise ValueError("Calcium_imaging must be 2D array (time × pixels)")
        
        self.t_slice_1 = time_slice_thre1
        self.t_slice_2_base = time_slice_thre2_base
        self.t_slice_2_peak = time_slice_thre2_peak
        self.method_1 = method_1
        self.method_2_base = method_2_base
        self.method_2_peak = method_2_peak
        self.dim_h = dim_h
        self.dim_w = dim_w
        if self.dim_h * self.dim_w != self.cal.shape[1]:
            raise ValueError(
                f"dim_h * dim_w ({self.dim_h * self.dim_w}) must equal number of pixels ({self.cal.shape[1]})"
                )
            
    def _apply_method(self, data, method, method_name):
        if method == "mean":
            return np.mean(data, axis=0)
        elif method == "maximum":
            return np.max(data, axis=0)
        elif method == "minimum":
            return np.min(data, axis=0)
        else:
            raise ValueError(f"{method_name} must be 'mean', 'maximum' or 'minimum'. Got: {method}")
               
    def _compute_thre_mask(self, thre1, thre2):
        data1 = self.cal[self.t_slice_1, :] if self.t_slice_1 is not None else self.cal
        
        val1 = self._apply_method(data1, self.method_1, 'method_1')
        mask1 = val1 > thre1
        
        base_data = self.cal[self.t_slice_2_base, :] if self.t_slice_2_base is not None else self.cal
        peak_data = self.cal[self.t_slice_2_peak, :] if self.t_slice_2_peak is not None else self.cal
        
        base_val = self._apply_method(base_data, self.method_2_base, 'method_2_base')
        peak_val = self._apply_method(peak_data, self.method_2_peak, 'method_2_peak')
        
        mask2 = (peak_val - base_val) > thre2
        mask = mask1 & mask2
        return mask, mask1, mask2
        
    @staticmethod
    def Single_curve_plot(Calcium_imaging: np.ndarray,
                          figsize: list= (30,5),
                          x_interval: int= 200):
        if Calcium_imaging.ndim != 2:
            raise ValueError("Calcium_imaging must be 2D array (time × pixels)")
        
        curve= Calcium_imaging[:, :].mean(axis=1)
        _, ax = plt.subplots(figsize=figsize)
        ax.plot(curve)
        ax.xaxis.set_major_locator(MultipleLocator(x_interval))
        plt.xticks(rotation='vertical')
        ax.set_xlabel("Time frame")
        ax.set_ylabel("Fluorescent level")
        ax.set_title("Fluorescence Curves")
        plt.tight_layout()

        
        
    def Thre_plot(self,  thre1, thre2):
        """
        Parameters to be optimized:
            thre1 (on the brightness),
            thre2 (on the KCL response)
        """
        mask, _, _ = self._compute_thre_mask(thre1, thre2)
        plt.imshow(np.reshape(mask, (self.dim_h, self.dim_w)))
        plt.title(f"Threshold Mask (thre1={thre1}, thre2={thre2})")

        
    def Thre_multi_plot(self,
                        thre1_list: list,
                        thre2_list: list,
                        figsize_scale: float = 4.0
                        ):
        """Plot all combinations of thresholds as subpanels with customizable figure size
    
        figsize_scale: multiplier for each subplot size (width and height)
        """
        n_rows = len(thre1_list)
        n_cols = len(thre2_list)
        fig, axs = plt.subplots(n_rows, n_cols, figsize=(figsize_scale*n_cols, figsize_scale*n_rows))
    
        # ensure axs is 2D array
        if n_rows == 1 and n_cols == 1:
            axs = np.array([[axs]])
        elif n_rows == 1:
            axs = axs[np.newaxis, :]
        elif n_cols == 1:
            axs = axs[:, np.newaxis]
        for i, t1 in enumerate(thre1_list):
            for j, t2 in enumerate(thre2_list):
                mask, _, _ = self._compute_thre_mask(t1, t2)
                axs[i, j].imshow(np.reshape(mask, (self.dim_h, self.dim_w)))
                axs[i, j].set_title(f"thre1={t1}, thre2={t2}")
                axs[i, j].axis('off')
         
        plt.tight_layout()

    
   
    
    def Cut_background(self, thre1, thre2):
        """----------------The idea of background removal---------------------------
        The mask as a bool vector can be used to delete the background pixels.
        However, this results to the calcium np.ndarray data with reduced columns and 
        without proper label, we may lose the information what is the X and Y
        positions of the pixels represented by these reduced rows.
     
        Thus, the idea is to store the information in a dataframe corresponding to
        the row-reduced calcium np.ndarray. The rows of the dataframe correspond to the 
        columns of the calcium np.ndarray, whereas the dataframe also has the X and Y
        positions
        """
        mask, _, _ = self._compute_thre_mask(thre1, thre2)
        mask_2d = np.reshape(mask, (self.dim_h, self.dim_w))
        coords = pd.DataFrame(np.column_stack(np.where(mask_2d)), columns=['Y', 'X'])
        return self.cal[:, mask], coords





















    
"""
2. PC_PROJ: Spatial SVD (Singular value decomposition) cluster pixels that share the same
            temporal response pattern.
      Also, dimension reduction using spacial PCA (principle component analysis), 
          since the spatial dimenstion (total pixel number) is much larger than time.
   
    Inputs (parameters):
        Calcium_imaging, np.ndarray, it can be original calcium imaging data, 
            or the BG_removal output with background removed.
        df_reduced contains coordinates of non-background pixels.
            The row number of df_reduced should be strictly the same as Calcium_imaging rows.
        time_start, time_end, the starting and end time frame index to cut a piece of time series
            (e.g., the window for a stimulated response) for the downstream analysis.
        n_PC, it is too much to compute all components (total pixel number)
        dim_h, dim_w, the pixel size of calcium imaging, it is output of ImportCZI().read_Cal()

    Outputs (attributes):
        PCs, All computed PCs (Principle Components) as np.array; 
            the 0th dimension defines which components;
            the 1st dimension contains the component information
            Notice the PCs are flatterned into one dimension (row followed by rows), 
                it needs to be reshaped to width and height dimensions.
        PC_plot(n), a function to plot the nth PC. 
            This plot can be used for PC choosing for projection.
        PC_proj(PC_indices), A projection of all chosen PCs, 
            PC_indices decide on the PC selection,
                in the form: "list(range(10,19))+list(range(0,2))"
          output an flatterned 1 dimension np.array image.    """

from sklearn.decomposition import PCA   
class PC_PROJ:
    def __init__(self,
        Calcium_imaging: np.ndarray,
        
        time_start: int,
        time_end:   int,
        n_PC:       int,
        dim_h:      int, 
        dim_w:      int,
        df_reduced: pd.DataFrame = None #Leave empty if Calcium_imaging is a full-pixel data):
        ):
        if Calcium_imaging.ndim != 2:
            raise ValueError("Calcium_imaging must be a 2D NumPy array (time x features).")
        if df_reduced is None:
            if dim_h is None or dim_w is None:
                raise ValueError("dim_h and dim_w must be provided.")
            if Calcium_imaging.shape[1] != dim_w*dim_h:
                raise ValueError(f"Calcium_imaging has {Calcium_imaging.shape[1]} pixels, "
                                 f"different from the defined image size {dim_h*dim_w}. "
                                 "There is no df_reduced to explain this disparity.")
        
        else:
            if Calcium_imaging.shape[1] != df_reduced.shape[0]:
                raise ValueError(
                    f"Row mismatch: Calcium_imaging has {Calcium_imaging.shape[1]} pixels, "
                    f"but df_reduced has {df_reduced.shape[0]} rows."
                )
            if 'Y' not in df_reduced.columns or 'X' not in df_reduced.columns:
                raise ValueError("df_reduced must contain 'Y' and 'X' columns.")
                
        self.cal= Calcium_imaging
        self.df_reduced= df_reduced
        self.start= time_start
        self.end= time_end
        self.n_PC= n_PC
        self.dim_h= dim_h
        self.dim_w= dim_w
        
        self.pca= PCA(n_components= self.n_PC)
        self.pca_dim_reduct= self.pca.fit_transform(self.cal[self.start:self.end,:])
        
        self.PC= self.pca.components_
        self.singular= self.pca.singular_values_
        
    """Important that Calcium_imaging should have 0's axis defining time,
        because PCA().fit(input), input is of shape (n_samples, n_features).
        here pixels are features.
        
        If the data has background pixel removed, one cannot visualize the PCs,
        since these PCs also don't have background pixles as well. We need to fill
        those background pixels as 0 to restore the full PCs""" 
       
    def _get_full_spatial_component(self):
        """
        Fill background pixels as 0 to restore full PCs.
        df_reduced contains coordinates of non-background pixels.
        """
        if self.df_reduced is None:
            # No spatial info, just return raw PCs as 2D array with shape (n_PC, n_pixels)
            return self.PC.reshape(self.PC.shape[0], self.dim_h, self.dim_w)
           
        else:
            # Reduced pixels, fill zeros for background
            stack = np.zeros((self.PC.shape[0], self.dim_h, self.dim_w), dtype=np.float64)
            coords = self.df_reduced[['Y', 'X']].to_numpy()
            stack[:, coords[:, 0], coords[:, 1]] = self.PC
            return stack
    
    def Get_PCs(self):
        """
        Returns:
        - PC: PCA components without background pixels (original reduced data)
        - fullPCs: PCA components with background pixels filled as 0
        """
        fullPCs = self._get_full_spatial_component()
        return self.PC, fullPCs.reshape(self.PC.shape[0], -1)
    
    def PCA_plot(self, pc_index:int):
        im= self._get_full_spatial_component()
        plt.imshow(im[pc_index,:,:])
        plt.title(f"PC {pc_index+1}")
        plt.axis('off')

        
    def PCA_multi_plot(self, 
                       n_panel_row: int, 
                       n_panel_col :int, 
                       pc_index_list: list,
                       figsize_scale= 4.0):
        """
        Plot multiple PCs in a grid
        Inputs:
            n_panel_row, n_panel_col : grid dimensions
            pc_index_list : 0-based PC indices to plot (titled 1-based)
        """
        fullPCs = self._get_full_spatial_component()
        #Ensure that the pc_index_list is within the range of available PCs.
        n_pcs = fullPCs.shape[0]
        if [i for i in pc_index_list if not 0 <= i < n_pcs]:
            raise ValueError(f"PC indices must be in range [0, {n_pcs-1}]. Got: {pc_index_list}")
        #Ensure the number of pannel is enough to plot all requested PCs.
        if len(pc_index_list) > n_panel_row * n_panel_col:
            raise ValueError(
                f"{len(pc_index_list)} PCs requested but grid only has "
                f"{n_panel_row * n_panel_col} panels."
            )
       
        _, axes = plt.subplots(
            n_panel_row, n_panel_col, 
            figsize=(figsize_scale*n_panel_col, figsize_scale*n_panel_row)
            )
        axes = np.array(axes).reshape(-1)  # flatten into 1D
       
        for ax, idx in zip(axes, pc_index_list):
            ax.imshow(fullPCs[idx,:,:])
            ax.set_title(f"PC {idx+1}")
            ax.axis('off')
       
        # hide unused axes
        # hide any unused panels
        for ax in axes[len(pc_index_list):]:
            ax.axis("off")
       
        plt.tight_layout()

        
    def Dimension_reduction(self):#Dimension reduction as pre-processing step can be used for ICA or other downstream analysis.
        return self.pca_dim_reduct
    
    



            
"""3. Neuron_Cluster: DBSCAN cluster of pixels in spatial principle components.
    
      Inputs (parameters):
          PCs, the second output of PC_PROJ, containing all pixels, np.ndarray
              2D array of shape (height, width)
          pc_binary_threshold, threshold used to change PCs into binary images, usually set as 0 or very small number
          height and width, (int,int), the spatial size of the calcium imaging.
              can be obtained from ImportCZI(...).read_Cal()[1],ImportCZI(...).read_Cal()[2].
          img_process_fun: method to process neuronal image generated from DBSCAN clustering. This is done neuronwise.
  
          ----------------------------Establish function for processing of binary images---------------------------
          #Here is an template doing first a morphological close then fill hole.
          def img_process_fun(img: NDArray[np.floating]):-> np.ndarray:
              from scipy.ndimage import binary_closing, binary_fill_holes       
              return binary_fill_holes(binary_closing(img, structure=np.ones((3,3)) ) )
        
              
      Outputs (attributes) for visualization and parameter learning:
          PC_DBSCAN, a function that perform DBSCAN clustering to segment neurons.
              The function output a dataframe with a neuron column called "Cluster" defining 
              which neuron each pixel belongs to.
          
         PC_DBSCAN_plot, a multi-pannel-plot function that visualize the effect of eps and min_samples
             on neuronal cluster effect for a defined PC
         PC_index_plot, plot all PCs when all parameters are defined.
     
     Output (attributes) for clustering outcome and visualization.
          Z_Project, a function perfrom z projection of all clustered PCs;
              the z-projection is done from the last of the defined list of PCs;
              when going to the previous PC, pixels already clustered in the next PC will be removed from
                  this previous PC. This is to avoid that the same neurons segmented twice;
             
             The output is that output a dataframe, rows representing XY coordinates, 
                  with a neuron column called "Cluster" defining, which neuron each pixel belongs to. 
                  The cluster may not be [1,2,3,...], but [1,3,10...], because some cluster indexes are filtered out.
                  
                  Notise that the output only contains positive pixel rows, without BG_define background, 
                      or DBSCAN defined noise, or size filtered pixels.
          A function that can be used to plot Z_Project 
""" 
from sklearn.cluster import DBSCAN
import seaborn as sns  
import numpy as np
from numpy.typing import NDArray
from typing import Callable, Optional
import matplotlib.pyplot as plt
import pandas as pd
from scipy.ndimage import binary_fill_holes, binary_closing
from skimage.measure import label, regionprops

class Neuron_Cluster:
    def __init__(self,
                PCs: np.ndarray,
                pc_binary_threshold: float | int=0,
                core_or_not: bool=False,#If only core, the neurons are smaller, losing border pixels
                height: int = 292, 
                width: int = 384,
                img_process_fun: Optional[Callable[[np.ndarray], np.ndarray]] = None):
        if not isinstance(PCs, np.ndarray):
            raise TypeError("PCs must be a numpy array")
        if PCs.ndim != 2:
            raise ValueError(f"Expected PCs shape (n_components, n_pixels), got {PCs.shape}")
        
        """The input PCs should be the fullPCs, the background pixels should not be abcent, though
        they can be set as 0, as they are define by BG_define as background."""
        _, n_pix = PCs.shape
        if n_pix != height * width:
            raise ValueError(
                f"Number of pixels ({n_pix}) does not match expected size "
                f"({height} × {width} = {height*width})"            )
            
        self.PCs = PCs                          # shape: (n_components, n_pixels)
        self.pc_binary_threshold = pc_binary_threshold
        self.core_or_not= core_or_not
        self.height = height
        self.width = width
        
        """Precompute binary versions of all PCs
        Notise that after this binary transformation, all backgound pixels defined in BG_define
            will become zero."""
        self.PC_binary = (self.PCs > self.pc_binary_threshold).astype(np.uint8)
        
        # Default image processing function: close then fill holes
        def default_img_process(img: np.ndarray) -> np.ndarray:
            return binary_fill_holes(binary_closing(img, structure=np.ones((3, 3))))

        if img_process_fun is None:
            self.img_process_fun = default_img_process
        else:
            if not callable(img_process_fun):
                raise TypeError(f"img_process_fun must be callable, got {type(img_process_fun)}")
            self.img_process_fun = img_process_fun
    

    
    def _mask_matrix_to_df(self, PC_binary, pc_index: int) -> pd.DataFrame:
        """
        Convert a 2D numpy array (image/matrix) into long-format DataFrame
        with columns: Y, X, value, Loc
        Parameter
        pc_index: which PC from the PCs is transformed into dataframe
        
        Attributes
        pd.DataFrame. Long format with columns:          
            - Y    : row index (0 = top)
            - X    : column index (0 = left)
            - value: pixel intensity / value
            - Loc  : flattened index = Y * width + X
        """
        # Create coordinate grid
        Y, X = np.indices((self.height, self.width))           # shape (h,w) for both
        df = pd.DataFrame({
            'Y':     Y.ravel(),
            'X':     X.ravel(),
            'binary': PC_binary[pc_index,:],
            'pc_index': pc_index})            
        # Optional: ensure integer types where it makes sense
        df['Y']    = df['Y'].astype(np.int32)
        df['X']    = df['X'].astype(np.int32)
        df['binary']  = df['binary'].astype(np.int64)   # safer for large images
        df['pc_index'] = df['pc_index'].astype(np.int16)
        
        return df


    def _dbscan (self, bi_df,  eps: float, min_samples: int):#has to run after _mask_matrix_to_df
        pos_df =bi_df[bi_df['binary'] == 1].copy()
        if pos_df.empty:
            raise ValueError(f"Empty mask, set down the pc_binary_threshold"  )
        cluster = DBSCAN(eps=eps, min_samples=min_samples).fit(pos_df.loc[:,['X','Y']])       
        pos_df['Cluster'] = cluster.labels_#Tag pixels by which neuron they belongs to       
        if self.core_or_not is True:
            pos_df= pos_df.iloc[cluster.core_sample_indices_].reset_index(drop=True)
           
        return pos_df[pos_df['Cluster']!=-1].reset_index(drop=True)
        #Choosing the pixels (rows of the dataframe) within clusters out of the noise.
   
    
    def _clusterwise_process(self, pos_df):
        if pos_df.empty:
            return pos_df
        if not callable(self.img_process_fun):
            raise TypeError(f"img_process_fun must be callable, got {type(self.img_process_fun)}")
        filled_dfs = []
        for cluster_id, group in pos_df.groupby("Cluster"):#Pre-processing clusterwise
            xmin, xmax = group.X.min(), group.X.max()#To speedup, perform preprocessing in cropped image
            ymin, ymax = group.Y.min(), group.Y.max()
            img = np.zeros((ymax-ymin+1, xmax-xmin+1), dtype=np.uint8)#df to matrix
            img[group.Y - ymin, group.X - xmin] = 1#df to matrix
            img_filled = self.img_process_fun(img)#Applying function here, input is matrix
            Y, X = np.where(img_filled)#matrix to df
            df_cluster = pd.DataFrame({"X": X + xmin,"Y": Y + ymin,"Cluster": cluster_id})#matrix to df
            filled_dfs.append(df_cluster)#Append df of different clusters
        return pd.concat(filled_dfs, ignore_index=True)


    def _pix_size_filter (self, denoised_df, min_pixel_size: int, max_pixel_size: int):
        if denoised_df.empty:
            return denoised_df
        cluster_sizes= denoised_df['Cluster'].value_counts()
        valid_clusters = cluster_sizes[
            (cluster_sizes >= min_pixel_size) &
            (cluster_sizes <= max_pixel_size) ].index
        return denoised_df[denoised_df["Cluster"].isin(valid_clusters)]

    @staticmethod
    def _roundness(group):
        xmin, xmax = group.X.min(), group.X.max()
        ymin, ymax = group.Y.min(), group.Y.max()
        img = np.zeros((ymax - ymin + 1, xmax - xmin + 1), dtype=np.uint8)
        img[group.Y - ymin, group.X - xmin] = 1
        return 1 - regionprops(label(img))[0].eccentricity

    def _roundness_filter(self, denoised_df, min_roundness: float = 0.0, max_roundness: float = 1.0):
        """Filter clusters by roundness = 1 - eccentricity (1 = circle, 0 = elongated)."""
        if denoised_df.empty:
            return denoised_df
        
        scores = denoised_df.groupby("Cluster").apply(self._roundness)
        valid_clusters = scores[(scores >= min_roundness) & (scores <= max_roundness)].index
        return denoised_df[denoised_df["Cluster"].isin(valid_clusters)]
 
    
    def PC_DBSCAN (self, pc_index: int, eps: float, min_samples: int,                   
                   min_pixel_size: int, max_pixel_size: int):
        """
        Parameter
        pc_index: which PC from the PCs is chosen to be clustered
        
        Parameters to be optimized:
            eps, neighborhood radius, key tuning parameters for DBSCAN. 
            min_samples, minimum points to form a dense region, key tuning parameters for DBSCAN
            min_pixel_size, max_pixel_size, threshold of spatial size to remove particles too small or too
                large to be considered as a neuronal soma.   
            
        Artributes
        A dataframe with XY coordinates of pixels 
            with a Cluster column defining which neuron each pixel belongs to.   
                """          
        bi_df = self._mask_matrix_to_df( self.PC_binary, pc_index)#output stored in self.df and self.index
        denoised_df = self._dbscan ( bi_df, eps, min_samples)#output stored in updated self.df and self.denoised_df
        filled_dfs = self._clusterwise_process(denoised_df)#clusterwise processing
        filt_df = self._pix_size_filter (filled_dfs, min_pixel_size, max_pixel_size)#output stored in self.filt_df
        #fill background and noise pixels to restore the full np.darray image
        self.filt_df= filt_df
        return filt_df
    
    def PC_DBSCAN_plot(self, pc_index: int, eps_list: list, min_samples_list: list,                     
                       min_pixel_size: int, max_pixel_size: int):
        """
        This plot helps to visualize the influence of eps, 
            on clustering result, the plot have subpannels that represent different combinations
            of these two parameters.
        This visualization can be performed under different filter sizes, to evaluate how small/large
            a particle that needs to be removed"""
        #The list input is in the format e.g., eps_list= [1,3,6...]
        plt.figure(figsize= (len(min_samples_list)*10,len(eps_list)*10))
        for i in range(len(eps_list)):
            for j in range(len(min_samples_list)):
                df_image= self.PC_DBSCAN (pc_index, eps_list[i], min_samples_list[j],
                                          min_pixel_size, max_pixel_size)
                
                panel = plt.subplot(len(eps_list), len(min_samples_list), 
                                    i * len(min_samples_list) + j + 1)
                #neuron defined by the "cluster1.core_sample_indices_" (keeping only cores)
                df_image= df_image.rename(columns= {'Cluster':'Neuron_indice'})
                plot=sns.scatterplot( x="X", y="Y", data= df_image,
                               hue='Neuron_indice',  palette='dark', legend=False, s=5)
                plot.set(xlim= (0,self.width), ylim= (0,self.height))
                plot.invert_yaxis()
                plt.title(f"eps={eps_list[i]}, Min_samples={min_samples_list[j]}")
                
    def PC_index_plot(self, pc_list: list, eps: int, min_samples: int, n_rows: int, 
                      min_pixel_size: int, max_pixel_size: int):
        """
        This plot gives a pannel of different PCs under a defined parameter setting.
            n_rows is the number of rows in this pannel, in case the pannels append to be to wide"""
        plt.figure(figsize= ((int(len(pc_list)/n_rows)+1)*10 , n_rows*10)  )
        for i in range(len(pc_list)):
                df_image= self.PC_DBSCAN (pc_list[i], eps, min_samples,
                                          min_pixel_size, max_pixel_size)
                
                panel = plt.subplot(n_rows, int(len(pc_list)/n_rows)+1,  i+1)
                #neuron defined by the "cluster1.core_sample_indices_" (keeping only cores)
                df_image= df_image.rename(columns= {'Cluster':'Neuron_indice'})
                plot=sns.scatterplot( x="X", y="Y", data= df_image,
                               hue='Neuron_indice',  palette='dark', legend=False, s=5)
                plot.set(xlim= (0,self.width), ylim= (0,self.height))
                plot.invert_yaxis()
                plt.title(f"PC index={pc_list[i]}")  

    
    """----------------------z_projection-------------------------------------------
    1. perform dbscan and size filter on the last (nth) binary pc
    2. remove all positive pixels in nth pc from (n-1)th binary pc
    3. perform dbscan and size filter on the (n-1)th binary pc
    4. keep on the iteration """  
    
    def __define_parameters__(self, 
                 pc_list:list, 
                 eps:int, 
                 min_samples:int,
                 min_pixel_size:int =50, 
                 max_pixel_size:int =10000,
                 min_roundness:float = 0, 
                 max_roundness:float = 1
                 ):
       
            
        self.pc_list= pc_list
        self.eps= eps
        self.min_samples= min_samples
        self.min_pixel_size= min_pixel_size
        self.max_pixel_size= max_pixel_size
        self.min_roundness= min_roundness
        self.max_roundness= max_roundness
    
    def _subtract_df1_from_df2(self, df1, df2):
        if df1.empty:
            return df2
        coords = set(zip(df1.X, df1.Y))
        mask = ~df2[['X','Y']].apply(tuple, axis=1).isin(coords)
        return df2[mask]

    def _z_project(self):
        dfs = pd.DataFrame()
        #next_id is a counter to ensure unique cluster IDs across different PCs.
        #in case the next PC has again index 0,1,2, which is the same as the previous PC.
        next_id = 0
        for pc_index in list(reversed(self.pc_list)):#Start from the last PC till the 0th.
            candidate_df = self._subtract_df1_from_df2(dfs, self._mask_matrix_to_df(self.PC_binary, pc_index))

            #If no unclaimed positive pixels remain for this PC, _dbscan would raise on an
            #all-empty mask. Skip clustering for this PC instead of crashing the whole loop.
            if not (candidate_df['binary'] == 1).any():
                continue         

            df_new = self._dbscan (candidate_df, self.eps, self.min_samples)
            df_new = self._clusterwise_process(df_new)
            df_new = self._pix_size_filter (df_new, self.min_pixel_size, self.max_pixel_size)
            df_new = self._roundness_filter(df_new, self.min_roundness, self.max_roundness)

            #Each new PC's clusters start their indexing from next_id.
            if not df_new.empty:
                local_labels = df_new['Cluster'].unique()
                remap = {old: new for new, old in enumerate(local_labels, start=next_id)}
                df_new['Cluster'] = df_new['Cluster'].map(remap)
                #Here the next_id is updated.
                next_id += len(local_labels)           

            dfs= pd.concat([dfs,df_new])
        return dfs
    
    
    def Z_Project (self, pc_list:list, eps:float, min_samples:int, 
                   min_pixel_size:int, max_pixel_size:int,
                    min_roundness:float, max_roundness:float ):
        self.__define_parameters__(pc_list, eps, min_samples, min_pixel_size, max_pixel_size, min_roundness, max_roundness)
        return self._z_project()
    
    def Z_Project_plot(self, pc_list:list, eps:float, min_samples:int, 
                   min_pixel_size:int, max_pixel_size:int, 
                   min_roundness:float, max_roundness:float,
                   dpi:int=100):    
        self.__define_parameters__(pc_list, eps, min_samples, min_pixel_size, max_pixel_size, min_roundness, max_roundness)
        df_image= self._z_project()
        plt.figure(figsize= (self.width/dpi, self.height/dpi), dpi=dpi)
        #neuron defined by the "cluster1.core_sample_indices_" (keeping only cores)
        df_image= df_image.rename(columns= {'Cluster':'Neuron_indice'})
        plot=sns.scatterplot( x="X", y="Y", data= df_image,
                       hue='Neuron_indice',  palette='dark', legend=False, s=5)
        plot.set(xlim= (0,self.width), ylim= (0,self.height))
        plot.invert_yaxis()
        plt.title(f"Neurons projected through PCs")
                
            
                    
"""4. Neuron_Seg: Output a calcium imaging matrix data and a dataframe that inform which pixel belong to which neuron.
    
      Inputs (parameters):
          Cal_raw_data, np.array, it must be original calcium imaging data, 
              not the BG_removal output with background removed!!!
              
          df_clust, pd.DataFrame, rows representing XY coordinates, 
              with a neuron column called "Cluster" defining, which neuron each pixel belongs to.
              Usually the output of Neuron_Cluster().Z_Project()      
              
      Outputs (attributes) for visualization and parameter learning:
          Output_all_Cal returns calcium data for every pixel in   
            df_clust. Axis 0 is time (frame order, unchanged from Cal_raw_data); axis 1 is space (pixels), ordered to match the rows of df_clust.
         
         Output_core_border, a function that returns calcium imaging data of core/borders of each neurons,
             and also returns the corresponding XY coordinates of these core/borders pixels, with the same order.
"""    
from skimage.segmentation import find_boundaries
class Neuron_Seg:
    
    def __init__(self,
                  Cal_raw_data: NDArray,
                  df_clust: pd.DataFrame,
                  height: int,
                  width: int,
                  pixel_border_width:int=3
        ):
        self.Cal_raw_data= Cal_raw_data
        self.df_clust= df_clust
        self.height= height
        self.width= width
        self.pixel_border_width=pixel_border_width

        if self.df_clust.empty:
            raise ValueError("df_clust is empty — no clusters to segment")
    
    def _output_all_Cal(self, df_clust):
        idx = (df_clust["X"] + self.width * df_clust["Y"]).to_numpy()
        return self.Cal_raw_data[:, idx]
    
    def _get_border(self,im):
        core=im.copy()
        border= np.zeros((im.shape[0], im.shape[1]), dtype=bool)
        for _ in range(self.pixel_border_width):
            layer=find_boundaries(core, connectivity=1, mode='inner', background=0)
            core[layer]=0#peal this one-pixel border and iterate to get a thicker border
            border[layer]=1#out2 is the border region of a single neuron (index as cell)
        return core, border

    def _clusterwise_sub_devide(self):
        Core_dfs = []
        border_dfs = []
        for cluster_id, group in self.df_clust.groupby("Cluster"):#Pre-processing clusterwise
            xmin, xmax = group.X.min(), group.X.max()#To speedup, perform preprocessing in cropped image
            ymin, ymax = group.Y.min(), group.Y.max()
            img = np.zeros((ymax-ymin+1, xmax-xmin+1), dtype=np.uint8)#df to matrix
            img[group.Y - ymin, group.X - xmin] = 1#df to matrix
            
            core, border = self._get_border(img)#Applying function here, input is matrix
            
            Y, X = np.where(core)#matrix to df
            df_cluster = pd.DataFrame({"X": X + xmin,"Y": Y + ymin,"Cluster": cluster_id})#matrix to df
            Core_dfs.append(df_cluster)#Append df of different clusters
            
            Y, X = np.where(border)#matrix to df
            df_cluster = pd.DataFrame({"X": X + xmin,"Y": Y + ymin,"Cluster": cluster_id})#matrix to df
            border_dfs.append(df_cluster)
            
        return pd.concat(Core_dfs, ignore_index=True),pd.concat(border_dfs, ignore_index=True)
    
    
    def Output_core_border(self):
        df_core,df_border= self._clusterwise_sub_devide()
        return df_core, df_border, self._output_all_Cal(df_core), self._output_all_Cal(df_border)
    
    def Output_all_Cal(self):
        return  self.df_clust, self._output_all_Cal(self.df_clust)   

    def Output_background(self):
        idx = (self.df_clust["X"] + self.width * self.df_clust["Y"]).to_numpy()
        return np.delete(self.Cal_raw_data, idx, axis=1) 

        
        
        
    
            
            
        
        
        
        
        
        
        
        
        
        
        
    
   